"""phase4_ripple_propagation

Revision ID: d8c1e55e6ddc
Revises: edca0f26b1f0
Create Date: 2026-09-17 20:34:23.466147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c1e55e6ddc'
down_revision: Union[str, Sequence[str], None] = 'edca0f26b1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ripple_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seed_package_id', sa.Integer(), nullable=False),
    sa.Column('seed_vulnerability_id', sa.Integer(), nullable=True),
    sa.Column('sbom_ingestion_id', sa.Integer(), nullable=True),
    sa.Column('vulnerability_scan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('affected_package_count', sa.Integer(), nullable=False),
    sa.Column('affected_application_count', sa.Integer(), nullable=False),
    sa.Column('direct_dependent_count', sa.Integer(), nullable=False),
    sa.Column('transitive_dependent_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('truncation_reason', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sbom_ingestion_id'], ['sbom_ingestions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seed_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seed_vulnerability_id'], ['vulnerabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vulnerability_scan_id'], ['vulnerability_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ripple_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ripple_analyses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_analyses_sbom_ingestion_id'), ['sbom_ingestion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_analyses_seed_package_id'), ['seed_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_analyses_seed_vulnerability_id'), ['seed_vulnerability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_analyses_vulnerability_scan_id'), ['vulnerability_scan_id'], unique=False)

    op.create_table('ripple_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.Column('shortest_path_length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(node_type = 'package' AND package_id IS NOT NULL AND application_id IS NULL) OR (node_type = 'application' AND application_id IS NOT NULL AND package_id IS NULL)", name='ck_ripple_node_reference'),
    sa.ForeignKeyConstraint(['analysis_id'], ['ripple_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'node_type', 'package_id', 'application_id', name='uq_ripple_node_identity')
    )
    with op.batch_alter_table('ripple_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ripple_nodes_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_nodes_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_nodes_package_id'), ['package_id'], unique=False)

    op.create_table('ripple_paths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('target_node_type', sa.String(length=50), nullable=False),
    sa.Column('target_package_id', sa.Integer(), nullable=True),
    sa.Column('target_application_id', sa.Integer(), nullable=True),
    sa.Column('path_nodes', sa.JSON(), nullable=False),
    sa.Column('path_length', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['ripple_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ripple_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ripple_paths_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_paths_target_application_id'), ['target_application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ripple_paths_target_package_id'), ['target_package_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ripple_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ripple_paths_target_package_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_paths_target_application_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_paths_analysis_id'))

    op.drop_table('ripple_paths')
    with op.batch_alter_table('ripple_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ripple_nodes_package_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_nodes_application_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_nodes_analysis_id'))

    op.drop_table('ripple_nodes')
    with op.batch_alter_table('ripple_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ripple_analyses_vulnerability_scan_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_analyses_seed_vulnerability_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_analyses_seed_package_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_analyses_sbom_ingestion_id'))
        batch_op.drop_index(batch_op.f('ix_ripple_analyses_project_id'))

    op.drop_table('ripple_analyses')
    # ### end Alembic commands ###
