"""phase2_dependency_intelligence

Revision ID: d9f29bbda768
Revises: 
Create Date: 2026-09-17 20:00:12.264784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f29bbda768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('purl', sa.String(length=500), nullable=True),
    sa.Column('bom_ref', sa.String(length=500), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecosystem', 'name', 'version', name='uq_package_ecosystem_name_version')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_ecosystem'), ['ecosystem'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_purl'), ['purl'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_application_project_name_version')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_project_id'), ['project_id'], unique=False)

    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('source_package_id', sa.Integer(), nullable=True),
    sa.Column('target_package_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'source_package_id', 'target_package_id', name='uq_dependency_app_source_target')
    )
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dependencies_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_source_package_id'), ['source_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dependencies_target_package_id'), ['target_package_id'], unique=False)

    op.create_table('sbom_ingestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('spec_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('dependency_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sbom_ingestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sbom_ingestions_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sbom_ingestions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sbom_ingestions_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sbom_ingestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sbom_ingestions_sha256'))
        batch_op.drop_index(batch_op.f('ix_sbom_ingestions_project_id'))
        batch_op.drop_index(batch_op.f('ix_sbom_ingestions_application_id'))

    op.drop_table('sbom_ingestions')
    with op.batch_alter_table('dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dependencies_target_package_id'))
        batch_op.drop_index(batch_op.f('ix_dependencies_source_package_id'))
        batch_op.drop_index(batch_op.f('ix_dependencies_application_id'))

    op.drop_table('dependencies')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_project_id'))

    op.drop_table('applications')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_purl'))
        batch_op.drop_index(batch_op.f('ix_packages_name'))
        batch_op.drop_index(batch_op.f('ix_packages_ecosystem'))

    op.drop_table('packages')
    # ### end Alembic commands ###
