"""phase5_structural_risk

Revision ID: fb81a1083406
Revises: d8c1e55e6ddc
Create Date: 2026-09-17 20:50:36.742919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb81a1083406'
down_revision: Union[str, Sequence[str], None] = 'd8c1e55e6ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('severity_weight', sa.Float(), nullable=False),
    sa.Column('centrality_weight', sa.Float(), nullable=False),
    sa.Column('blast_radius_weight', sa.Float(), nullable=False),
    sa.Column('application_criticality_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_profiles_project_id'), ['project_id'], unique=False)

    op.create_table('risk_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_scan_id', sa.Integer(), nullable=True),
    sa.Column('risk_profile_id', sa.Integer(), nullable=True),
    sa.Column('weight_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('vulnerability_count', sa.Integer(), nullable=False),
    sa.Column('scored_count', sa.Integer(), nullable=False),
    sa.Column('unscored_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vulnerability_scan_id'], ['vulnerability_scans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_analyses_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_analyses_risk_profile_id'), ['risk_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_analyses_vulnerability_scan_id'), ['vulnerability_scan_id'], unique=False)

    op.create_table('risk_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_version', sa.String(length=50), nullable=True),
    sa.Column('severity_normalized', sa.Float(), nullable=True),
    sa.Column('pagerank', sa.Float(), nullable=True),
    sa.Column('betweenness', sa.Float(), nullable=True),
    sa.Column('centrality_score', sa.Float(), nullable=True),
    sa.Column('centrality_approximate', sa.Boolean(), nullable=False),
    sa.Column('affected_downstream_package_count', sa.Integer(), nullable=False),
    sa.Column('affected_application_count', sa.Integer(), nullable=False),
    sa.Column('package_reach', sa.Float(), nullable=False),
    sa.Column('application_reach', sa.Float(), nullable=False),
    sa.Column('blast_radius_score', sa.Float(), nullable=True),
    sa.Column('max_application_criticality', sa.String(length=50), nullable=True),
    sa.Column('application_criticality_score', sa.Float(), nullable=True),
    sa.Column('dependency_depth', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('priority_band', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['risk_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'package_id', 'vulnerability_id', name='uq_risk_result_analysis_package_vuln')
    )
    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_results_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_results_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_results_vulnerability_id'), ['vulnerability_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criticality_tier', sa.String(length=50), server_default='MEDIUM', nullable=False))
        batch_op.add_column(sa.Column('criticality_score', sa.Float(), server_default='0.5', nullable=False))
        batch_op.add_column(sa.Column('criticality_source', sa.String(length=50), server_default='default', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('criticality_source')
        batch_op.drop_column('criticality_score')
        batch_op.drop_column('criticality_tier')

    with op.batch_alter_table('risk_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_results_vulnerability_id'))
        batch_op.drop_index(batch_op.f('ix_risk_results_package_id'))
        batch_op.drop_index(batch_op.f('ix_risk_results_analysis_id'))

    op.drop_table('risk_results')
    with op.batch_alter_table('risk_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_analyses_vulnerability_scan_id'))
        batch_op.drop_index(batch_op.f('ix_risk_analyses_risk_profile_id'))
        batch_op.drop_index(batch_op.f('ix_risk_analyses_project_id'))

    op.drop_table('risk_analyses')
    with op.batch_alter_table('risk_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_profiles_project_id'))

    op.drop_table('risk_profiles')
    # ### end Alembic commands ###
